- all_in_one_dresser :
  prodname : All in one Dresser
  linkname: all_in_one_dresser
  des: all in one dresser is an easy-to-use protectant that restores a deep black look, enhances shine, and protects vinyl, rubber, and plastic surfaces against harmful UV solar rays.
  FEATURES: 
  - Make trim shine like new  
  - Take years off your old beater
  - Protect tires, bumpers, trim
  - Create a super shine on any textured plastic
  des2: Easily coat dashboards, door panels, vinyl seats Restores and maintains flexibility, stretchability Helps to prevent cracking, tearing, fading, and discoloring
  DIRECTION: 
  -  Clean surface with OddO cleaner
  -  Dilute according to desired needs in spray bottle oe in a cup( 1:1).
  -  Apply Conditioner onto a sponge or applicatorpad
  -  Spread dressing over the entire workpiece, then work and rub deep into the surface.
  -  Buff off any excess residue with a microfiber towel.
  img:
  - 
    src: /cp/all_in/all_iin_one_5ltr.jpg
    alt: all_iin_one_5ltr
  -
    src: /cp/all_in/all_in_one_5_ltr_1.jpg
    alt: all_iin_one_5ltr
  - 
    src: /cp/all_in/all_in_one_5ltr_1.jpg  
    alt: all_iin_one_5ltr
  - 
    src: /cp/all_in/all_in_one_5_ltr.jpg
    alt: all_iin_one_5ltr  
  - 
    src: /cp/all_in/all_in_one_5ltr.jpg 
    alt: all_iin_one_5ltr 
  - 
    src: /cp/all_in/all_in_one_dresser_1ltr.jpg
    alt: all_iin_one_5ltr 
- All-Purpose-Cleaner :
  linkname: all-purpose-cleaner
  prodname :  All-Purpose-Cleaner
  des: OddO All-Purpose-Cleaner is the best APC on the market today. It’s the best because it uses the most costly ingredients.A spray-on liquid that cleans virtually any surface or material.Cleans, dissolves all types of organic, inorganic, stains as well as biological stains. Removes biological odors permanently.Anytime you need to remove any type of stain on a surface or in a material.
  FEATURES: 
  - All purpose cleaner that’s safe for virtually all interior surfaces.  
  - Cleans leather, vinyl, rubber, plastic, cloth seats and door panels.
  des2: 
  DIRECTION: 
  -  Dilute according to desired needs in spray bottle( 1:9 ).
  -  Apply to stained area, then allow to penetrate 10-60 seconds.
  -  Blot with a clean absorbent cloth.
  img:
  -  
    src: /cp/All-Purpose-Cleane/apc_5ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/All-Purpose-Cleane/apc_5ltr1.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/All-Purpose-Cleane/apc_5ltr_2.jpg 
    alt: all_iin_one_5ltr
  -  
    src: /cp/All-Purpose-Cleane/apc_1ltr.jpg
    alt: all_iin_one_5ltr  
  -  
    src: /cp/All-Purpose-Cleane/apc_1ltr1.jpg
    alt: all_iin_one_5ltr  
  -  
    src: /cp/All-Purpose-Cleane/apc_1ltr_2.jpg
    alt: all_iin_one_5ltr
- Color-Foam :
  linkname: color-foam
  prodname :  Color Foam
  des: A concentrated, high performance, pH neutral soap blend that lubricates, shines and protects as you wash with wax . color foam is a powerful concentrated shampoo and gloss enhancer formulated to bring out a vibrant shine on all paint colors, making any car look just waxed and detailed!
  FEATURES: 
  - Created color foam (pink,green,yellow,blue)  
  - Make any car look just waxed and detailed
  - Bring out the vibrant shine on any paint color
  - Does not strip any other wax or sealant products
  - Rinses clean without streaks
  - pleasent scent
  des2: 
  DIRECTION: 
  - Dilute 1:50 in foaming jet cylinder and 1:9 high pressure washer
  - Fill Foam Cannon or  Foam Gun canister with 900ml water with 100 ml wash&wax
  - Screw sprayer lid back onto canister, shake well.
  - Attach canister and sprayer to nozzle or pressure washer.
  - Squeeze handle to spray tons of suds onto your vehicle.
  img:
  -  
    src: /cp/Color-Foam/color_foqm_1_ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Color-Foam/color_foam_1ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Color-Foam/color_foqm_1ltr.jpg
    alt: all_iin_one_5ltr 
- Dashboard-Dresser :
  linkname: dashboard-dresser
  prodname : Dashboard Dresser
  des: OddO dashboard dresser is Specially formulated to restore gloss on vinyl,plastic surfaces, and protect against UVrays, The oddo Dashboard Polish protects and shines your interiors of your car, bike, and othervehicles. It provides an instant shine to your dashboard, Plastic and Vinyl parts of your car,bike and motorcycles and preserves the interiors of your vehicle. When used regularly on your cars,bikes, and vehicles, it resists fading, drying, cracking and maintains a fresh look of your vehicle’sinteriors.
  FEATURES: 
  - Restore, Protect and Prevent Car/Bike Interiors
  - oddo Dashboard Polish helps keep your car interiors like dashboard shine and restore the
  - shine of your dull, faded interiors. By applying the oddo Dashboard Polish, you can preventthe fading, drying and cracking of your car interiors and protect it from the damage of harsh UVrays.
  - UV Rays Resistant
  des2: 
  DIRECTION: 
  - Ensure that surface is clean and free from dust, dirt, rust, grease or oil. If needed, wash and dry with OddO all purpose cleaner
  - Take product on sponge applicator &amp; spread it evenly on the surface
  - For dull and faded surfaces, two or more applications will be required
  img:
  -  
    src: /cp/Dashboard-Dresser/dash_5_ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Dashboard-Dresser/dash_5ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Dashboard-Dresser/dash_5ltr_1.jpg
    alt: all_iin_one_5ltr  
  -  
    src: /cp/Dashboard-Dresser/dash_1_ltr.jpg
    alt: all_iin_one_5ltr 
  -  
    src: /cp/Dashboard-Dresser/dash_1_ltr_1.jpg
    alt: all_iin_one_5ltr  
  -  
    src: /cp/Dashboard-Dresser/dash_ltr.jpg
    alt: all_iin_one_5ltr
- Degreaser :
  linkname: degreaser
  prodname : Degreaser
  des: PERFECT DEGREASER is a concentrated water base power cleaner and degreaser. It dilutes with water and cleans a variety of surfaces. For engines and greasy door jams,For medium duty degreasing. Safe for most under-the-hood rubber and plastic parts. Great for stubborn spots.It can be used to clean and remove, adhesives - blood - car oils and grease, crayon markings, ink from magic markers, lipstick and other cosmetic stains, chewing gum, sticker, emblem, trim and molding adhesive, oily soap scum etc
  FEATURES: 
  - Water Based Formula
  - Removes grease, grime and dirt
  - Cleans engines, trunks, door jams, wheels, tire and rims
  - Safe for exterior parts
  des2: 
  DIRECTION: 
  - Dilute according to desired needs in spray bottle( 1:4).
  - Spray directly onto the surface to be cleaned and allow the product to dwell and penetrate for up to one minute.
  - Wipe the area clean using a clean microfiber towel or rinse clean with water.
  img:
  -  
    src: /cp/Degreaser/degreqser_5_ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Degreaser/degreaser_5ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Degreaser/degreaser_5ltr_1.jpg
    alt: all_iin_one_5ltr  
  -  
    src: /cp/Degreaser/degreaser_1ltr.jpg
    alt: all_iin_one_5ltr 
  -  
    src: /cp/Degreaser/degreaser_1ltr1.jpg
    alt: all_iin_one_5ltr  
  -  
    src: /cp/Degreaser/degreaser_1ltr_2.jpg
    alt: all_iin_one_5ltr
- Foam-Shampoo:
  linkname: foam-shampoo
  prodname : Foam-Shampoo
  des: FOAM SHAMPOO is the perfect maintenance shampoo that cleans and enhances any color paintwork with extreme foaming bubbles for the perfect scratch-free shine without stripping wax or sealant.Multi-function,pH balanced biodegradable liquid car wash shampoo.  Can be used with traditional hose and bucket technique or foam gun/foam cannon.
  FEATURES: 
  - Gently cleanse car with unending wash bubbles
  - Create a slick wash surface to protect paint
  - Achieve maximum foam with minimal product
  - Easily cut through heavy dirt, grime and road film
  - Bucket Wash – Foam Gun – Foam Cannon.
  des2: 
  DIRECTION: 
  - Dilute 1:50 in foaming jet cylinder and 1:9 high pressure washer
  - Fill Foam Cannon or  Foam Gun canister with 900ml water with 100 ml foam shampoo
  - Screw sprayer lid back onto canister, shake well.
  - Attach canister and sprayer to nozzle or pressure washer.
  - Squeeze handle to spray tons of suds onto your vehicle.
  img:
  -  
    src: /cp/Foam-Shampoo/foam_20_ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Foam-Shampoo/foqm_20ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Foam-Shampoo/foam_20ltr.jpg
    alt: all_iin_one_5ltr  
- Glass-Clean:
  linkname: glass-clean
  prodname : Glass Clean
  des: OddO Glass Cleaner delivers a powerful cleaning formula matched with a streak-free experience that is also safe for tinted windows.Having crystal clear glass is important! Clean windows improve visibility and provide a safe driving experience for all drivers. As the product removes and restores perfect vision to your glass, it also reduces static cling and energy to lower the amount of dust that settles.
  FEATURES: 
  - Powerful Formula Cuts through Dirt, Dust, Grease, Grime and other Film Contaminants
  - Cleans and Lubricates without Streaking or Smearing
  - Suitable for All Surfaces including Tinted Windows and Tablet Screens
  - Non-streak, no-haze formula leaves glass crystal clear.
  - Non-Ammonia - safe for all glass including tinted windows.
  - Removes oily smoker’s film,vinyl fog,oily fingerprints and pet smudges.
  des2: 
  DIRECTION: 
  - Dilute according to desired needs in spray bottle(1:9 ).
  - Spray a light mist of OddO Glass Cleaner onto a window or a section of glass.
  - wipe a window or section of a window so that you spread the glass cleaner over the entire area to be cleaned.  The liquid glass cleaner will go to work dissolving any dirt or film.  Flip the towel to the other side, which is still clean, and re-wipe this window or section of a window.  At this point, the bulk of any dirt or film-build should be on this towel.  Place this towel off to the side in a clean container for washing later.
  img:
  -  
    src: /cp/Glass-Clean/glass_5ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Glass-Clean/glass_5_ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Glass-Clean/glass_5tr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Glass-Clean/glass_1ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Glass-Clean/glass_ltr(1).jpg
    alt: all_iin_one_5ltr 
  -  
    src: /cp/Glass-Clean/glass_1ltr(2).jpg
    alt: all_iin_one_5ltr
- Tyre-Dresser:
  linkname: tyre-dresser
  prodname : Tyre Dresser
  des: OddO tyre dresser is a water-based dressing that allows anyone to recreate bright wet shine of brand new cars on tires and other rubber around your car. It works fast, it’s easy to apply and the results You’ll get incredible gloss from a water-based protectant.Creates a deep, dark shine on rubber surfaces. Protects against damage from the sun’s ultraviolet rays. Holds up without running off in wet weather or when washing vehicle.
  FEATURES: 
  - Lay down a shine that will get you kicking your tires all over again
  - Enhance a deep black shine
  - Restore new black look to tyre
  - Help prevent future fading from sunlight
  - Achieve perfect non-slippery feel
  des2: 
  DIRECTION: 
  - Clean surface with OddO degreaser
  - Dilute according to desired needs in spray bottle or in a cup ( 1:1).
  - Apply Conditioner onto a sponge or applicatorpad
  - Spread dressing over the entire workpiece, then work and rub deep into the surface.
  - Buff off any excess residue with a microfiber towel.
  img:
  -  
    src: /cp/Tyre-Dresser/tyre_5_ltr(1).jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Tyre-Dresser/tyre_5_ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Tyre-Dresser/tyre_5ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Tyre-Dresser/tyre_1ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Tyre-Dresser/tyre_1ltr(1).jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Tyre-Dresser/tyre_1ltr(2).jpg
    alt: all_iin_one_5ltr
- Wash-Wax:
  linkname: wash-wax
  prodname : Wash & Wax
  des: A concentrated, high performance, pH neutral soap blend that lubricates, shines and protects as you wash. Wash and wax is a powerful concentrated shampoo and gloss enhancer formulated to bring out a vibrant shine on all paint colors, making any car look just waxed and detailed! 
  FEATURES: 
  - High suds formula safely removes dirt and other contaminants
  - Make any car look just waxed and detailed
  - Bring out the vibrant shine on any paint color
  - Does not strip any other wax or sealant products
  - Rinses clean without streaks
  - pleasent scent
  des2: 
  DIRECTION: 
  - Dilute 1:50 in foaming jet cylinder and 1:9 high pressure washer
  - Fill Foam Cannon or  Foam Gun canister with 900ml water with 100 ml wash&wax
  - Screw sprayer lid back onto canister, shake well.
  - Attach canister and sprayer to nozzle or pressure washer.
  - Squeeze handle to spray tons of suds onto your vehicle.
  img:
  - 
    src: /cp/Wash-Wax/wax_5ltr(1).jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wax_5ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wax_1ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wax_1ltr(1).jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wash_wax_1ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wash_wax_5ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wax_10_ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wax_10ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wax_10ltr(1).jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wax_20ltr.jpg
    alt: all_iin_one_5ltr
  -  
    src: /cp/Wash-Wax/wax_20ltr(1).jpg
    alt: all_iin_one_5ltr
